CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
    user_id INT PRIMARY KEY,
    score INT,
    
    FOREIGN KEY (user_id) REFERENCES users(id)
)